name: build_and_release

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish
      run: dotnet publish BetterNTE.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o out

    - name: Package into ZIP
      run: Compress-Archive -Path out\* -DestinationPath BetterNTE-windows-x64.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: BetterNTE-windows-x64.zip
        generate_release_notes: true
        draft: false
        prerelease: false